# Generated by Django 3.2 on 2025-09-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('letterboxd_uri', models.URLField()),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
