# Generated by Django 3.2 on 2025-09-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
